# Generated by Django 2.0 on 2017-12-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('step', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('fio', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram User',
            },
        ),
    ]
