# Generated by Django 2.0 on 2017-12-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20171206_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockio_api_keys_btc', models.CharField(blank=True, max_length=250, null=True)),
                ('blockio_api_keys_ltc', models.CharField(blank=True, max_length=250, null=True)),
                ('blockio_sercret_pin', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Настройки бота',
                'verbose_name': 'Настройки бота',
            },
        ),
        migrations.AddField(
            model_name='botuser',
            name='amount_btc_withdraw',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='btc_wallet',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='wallet_btc_withdraw',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
