# Generated by Django 2.0 on 2017-12-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='balance',
            new_name='btc_balance',
        ),
    ]
