# Generated by Django 2.0 on 2017-12-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20171208_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='phone_number',
            field=models.CharField(blank=True, default='USD', max_length=120, null=True),
        ),
    ]
