# Generated by Django 2.0 on 2017-12-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20171213_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Txs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name', models.CharField(blank=True, max_length=250, null=True)),
                ('date_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('wallet', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
