# Generated by Django 2.0 on 2017-12-15 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_txs'),
    ]

    operations = [
        migrations.AddField(
            model_name='txs',
            name='bot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.BotUser'),
        ),
        migrations.AddField(
            model_name='txs',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='txs',
            name='summa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
