# Generated by Django 2.0 on 2017-12-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20171215_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='txs',
            old_name='tx_name',
            new_name='trans_id',
        ),
    ]
