# Generated by Django 2.0 on 2017-12-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20171216_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='language',
            new_name='lang',
        ),
    ]
