# Generated by Django 2.0 on 2017-12-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20171224_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='text_eng',
            field=models.TextField(blank=True, null=True),
        ),
    ]
